#!/bin/bash

#setup master
host=$1
if [ -z "$host" ]; then
  host="localhost"
fi

MASTER_HOST=$(gethostip -d "$host")
MASTER_PORT="11311"

#source ROS-settings
export ROS_MASTER_URI="http://$MASTER_HOST:$MASTER_PORT"
source /opt/ros/kinetic/setup.bash

#update RPi

# Do we have a setupfile?
if [ ! -f ~/ros/rossetup-rpi ]; then
    cp ~/rpicross_notes/scripts/rossetup-rpi ~/ros/rossetup-rpi
fi

# Set ROS_MASTER_URI
sed -i "s|.*ROS_MASTER_URI.*|export\ ROS_MASTER_URI=$ROS_MASTER_URI|g" ~/ros/rossetup-rpi

# Update on rpi
scp -o StrictHostKeyChecking=no ~/ros/rossetup-rpi rpizero-local:~/ros/

#get rpi-hostname from ssh-config
#RPI_ADDR=$(ssh -v $RPI_SSH -o BatchMode=yes -o ConnectionAttempts=1 -o StrictHostKeyChecking=no true ' ' 2>&1 | grep 'Authenticated to' | cut -d' ' -f3)

